
changelog:
  categories:
    - title: ✨ Features
      labels: ["feature"]
    - title: 🐛 Fixes
      labels: ["fix", "bug"]
    - title: 🧪 Tests
      labels: ["test"]
    - title: 🔧 Other
      labels: ["refactor", "chore", "*"]
  tag_template: "v${{ version }}"
  name_template: "Release v${{ version }}"
  version_resolver:
    strategy: "auto"
    source: "changelog"
    prefix: "v"

