
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2  # Use the desired version of mypy
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini]
        additional_dependencies:
          - types-requests
>>>>>>> 775b785 (Initialize PristineRepo with merged files)
