version: '3.8'
services:
  primeengineai:
    build: ./PrimeEngineAI
    ports:
      - "8001:8000"

  gpu_sieve:
    build: ./gpu_sieve
    ports:
      - "8002:8000"

  remainder_analysis:
    build: ./remainder_analysis
    ports:
      - "8003:8000"

  primality_test:
    build: ./primality_test
    ports:
      - "8004:8000"

  orchestrator:
    build: ./orchestration
    ports:
      - "8000:8000"
    depends_on:
      - primeengineai
      - gpu_sieve
      - remainder_analysis
      - primality_test
