function Docs {
    \ = "C:\Users\leebo\Desktop\PrimeEngineAI_UAT\docs"
    if (-not (Test-Path \)) { New-Item -ItemType Directory -Path \ | Out-Null }

    @'
# PrimeEngine Documentation

This was auto-generated by ReflexTools.psm1 during recovery.
'@ | Set-Content "\\index.md"

    Write-Host "📄 index.md generated at \"
}
Export-ModuleMember -Function Docs
