name: CI/CD Automation

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensures submodules are initialized

      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Install Dependencies
        run: npm install

      - name: Verify Jest Installation
        run: npm list jest || npm install --save-dev jest

      - name: Run Tests
        run: npm test
