# 🔒 Workflow disabled by ReflexOps
name: DISABLED: automation.yml
on:
  workflow_call:
    types: [disabled]
jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
    - run: echo '⛔ automation.yml has been disabled by ReflexOps'
