# 🔒 Workflow disabled by ReflexOps
name: DISABLED: ci_cd_fresh.yml
on:
  workflow_call:
    types: [disabled]
jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
    - run: echo '⛔ ci_cd_fresh.yml has been disabled by ReflexOps'
