# 🔒 Deprecated by ReflexOps
name: Tombstoned: ci_cd_fresh.yml
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tombstone:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated Workflow Exit
        run: echo '🛑 ci_cd_fresh.yml is deprecated and exits silently.'
