# 🔒 Workflow disabled by ReflexOps
name: DISABLED: prime.sdlc.flowmap.yml
on:
  workflow_call:
    types: [disabled]
jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
    - run: echo '⛔ prime.sdlc.flowmap.yml has been disabled by ReflexOps'
