name: ReflexOps Notify

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Read badge
        run: |
          echo "BADGE=$(cat .github/reflexops/.reflexops-badge.md)" >> $GITHUB_ENV

      - name: Send webhook
        env:
          WEBHOOK_URL: ${{ secrets.NOTIFY_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" ^
            -d "{\"text\": \"📢 ReflexOps Audit Result:\n$env:BADGE\"}" ^
            $env:WEBHOOK_URL
