name: Optional Repo Sync

on:
  workflow_dispatch:
    inputs:
      run_sync:
        description: "Sync individual engine repos from ExoSuite?"
        required: true
        default: "no"

jobs:
  conditional-sync:
    if: ${{ github.event.inputs.run_sync == 'yes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Sync Script
        run: python3 sync_exosuite_repos.py